# start: docker-compose -f docker-compose.yml -f docker-compose.logging.yml up -d --build
# stop: docker-compose -f docker-compose.yml -f docker-compose.logging.yml down --rmi local
# For elasticsearch to work with docker toolbox
#  docker-machine ssh
#  sudo sysctl -w vm.max_map_count=262144
#
# After graylog startup you need manually create UPD input on port 12201 to receive logging messages from application
version: '3.7'
services:
  mongo:
    image: mongo:3.6
    networks:
      - network2
    volumes:
      - mongo_graylog_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - network2
  graylog:
    image: graylog/graylog:2.5
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://192.168.99.100:9001/api
    ports:
      - 9001:9000
      - 12201:12201
      - 12201:12201/udp
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - network2
networks:
  network2:
    driver: bridge
volumes:
  mongo_graylog_data:
    driver: local