# Start container using docker-compose.yml in foreground mode
# docker-compose up

# Start container using docker-compose.yml in foreground mode, rebuild any existing images
# docker-compose up --build

# Start container using docker-compose.yml in detached mode
# docker-compose up -d

# Stop all containers started via docker-compose and delete them
# docker-compose down

# Output log content of all running containers
# docker-compose logs

# Restart specified service/container
# docker-compose restart <service name>

# FOR DEPLOYING WAR ARCHIVES ALREADY BUILT ON LOCAL MACHINE
version: '3.7'
# Define anchor definition for healthcheck functionality
x-healthcheck:
  &health_check
  interval: 1m
  timeout: 10s
  retries: 2
  start_period: 2m
# Services definition
services:
  # Germes mysql database server
  mysql:
    build:
      context: germes-presentation-admin
      dockerfile: src/main/resources/docker/mysql.dockerfile
      #logging:
      # driver: none
    networks:
      - network1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=germes
      - MYSQL_PASSWORD=germes
      - MYSQL_DATABASE=germes
    env_file:
      - mysql.env
    command: ['--collation-server=utf8mb4_unicode_ci', '--character-set-server=utf8mb4']
    volumes:
      - germes-mysql-data:/var/lib/mysql
    healthcheck:
      << : *health_check
      test: mysql -ugermes -pgermes -e "SELECT version();"
  # Germes admin application
  admin:
    build:
      context: germes-presentation-admin
      dockerfile: src/main/resources/docker/admin-jetty.dockerfile
    ports:
      - "9000:8080"
    networks:
      - network1
    depends_on:
      - mysql
    entrypoint: bash -c "sleep 5s && java -jar /usr/local/jetty/start.jar"
    healthcheck:
      << : *health_check
      test: curl -f http://localhost:8080 || exit 1
  # Germes client application
  client:
    build:
      context: germes-presentation-web
      dockerfile: src/main/resources/docker/client-jetty.dockerfile
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      - mysql
    entrypoint: bash -c "sleep 5s && java -jar /usr/local/jetty/start.jar"
    healthcheck:
      << : *health_check
      test: curl -f http://localhost:8080 || exit 1
# Networks definition
networks:
  network1:
    driver: bridge
# Volumes definition
volumes:
  germes-mysql-data: