version: '3.7'
services:
  swagger:
    build:
      context: germes-client
      dockerfile: src/main/resources/docker/swagger-local-build.dockerfile
    ports:
      - "8000:8080"
    environment:
      - SWAGGER_JSON=/opt/swagger.json