# Start container using docker-compose.yml in foreground mode
# docker-compose [-f docker-compose-filename] up

# Start container using docker-compose.yml in foreground mode, rebuild any existing images
# docker-compose [-f docker-compose-filename] up --build

# Start container using docker-compose.yml in detached mode
# docker-compose [-f docker-compose-filename] up -d

# Stop all containers started via docker-compose and delete them
# docker-compose [-f docker-compose-filename] down

# Output log content of all running containers
# docker-compose [-f docker-compose-filename] logs [service]

# Restart specified service/container
# docker-compose [-f docker-compose-filename] restart <service name>

# OVERRIDING base Jetty specific settings for Payara specific settings
version: '3.7'
# Services overriding
services:
  admin:
    build:
      dockerfile: germes-presentation-web/src/main/resources/docker/payara-maven.dockerfile
    ports:
      - "9000:8080"
      - "4849:4848"
    entrypoint: bash -c "sleep 5s && asadmin start-domain -v"
  client:
    build:
      dockerfile: germes-presentation-web/src/main/resources/docker/payara-maven.dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - admin
    entrypoint: bash -c "sleep 120s && asadmin start-domain -v"