version: '3.7'
services:
  swagger:
    build:
      context: .
      dockerfile: germes-client/src/main/resources/docker/swagger-container-build.dockerfile
    ports:
      - "8000:8080"
    environment:
      - SWAGGER_JSON=/opt/swagger.json