alter table if exists ACCOUNT drop constraint if exists FK9rxadd7hdlmarov6qbvaot0po;
alter table if exists ACCOUNT drop constraint if exists FK4cfkq2sywnlcu6fxm9xbrmsjs;
alter table if exists CITIES drop constraint if exists FKbe39gncbw7tmfjfamr00x4qjv;
alter table if exists CITIES drop constraint if exists FKktfg6x187el29cnyjhhpvawca;
alter table if exists STATIONS drop constraint if exists FKldqyeie4uufe44knj6i4x2csv;
alter table if exists STATIONS drop constraint if exists FKqn5h21f3qh4noflqab0hmw7oc;
alter table if exists STATIONS drop constraint if exists FKo539o7bif6yu9a1w38n8fcpmd;
drop table if exists ACCOUNT cascade;
drop table if exists CITIES cascade;
drop table if exists STATIONS cascade;
create table ACCOUNT (ID  serial not null, CREATED_AT timestamp not null, MODIFIED_AT timestamp, CREATED_BY int4, MODIFIED_BY int4, primary key (ID));
create table CITIES (ID  serial not null, CREATED_AT timestamp not null, MODIFIED_AT timestamp, DISTRICT varchar(32), NAME varchar(32) not null, REGION varchar(32) not null, CREATED_BY int4, MODIFIED_BY int4, primary key (ID));
create table STATIONS (ID  serial not null, CREATED_AT timestamp not null, MODIFIED_AT timestamp, APARTMENT varchar(16), HOUSE_NO varchar(16) not null, STREET varchar(32) not null, ZIP_CODE varchar(10) not null, X float8, Y float8, PHONE varchar(16), TRANSPORT_TYPE varchar(255) not null, CREATED_BY int4, MODIFIED_BY int4, CITY_ID int4 not null, primary key (ID));
alter table if exists CITIES add constraint UK_mjjeh6je35mtsmrdm92x6rd1a unique (REGION);
alter table if exists ACCOUNT add constraint FK9rxadd7hdlmarov6qbvaot0po foreign key (CREATED_BY) references ACCOUNT;
alter table if exists ACCOUNT add constraint FK4cfkq2sywnlcu6fxm9xbrmsjs foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists CITIES add constraint FKbe39gncbw7tmfjfamr00x4qjv foreign key (CREATED_BY) references ACCOUNT;
alter table if exists CITIES add constraint FKktfg6x187el29cnyjhhpvawca foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATIONS add constraint FKldqyeie4uufe44knj6i4x2csv foreign key (CREATED_BY) references ACCOUNT;
alter table if exists STATIONS add constraint FKqn5h21f3qh4noflqab0hmw7oc foreign key (MODIFIED_BY) references ACCOUNT;
alter table if exists STATIONS add constraint FKo539o7bif6yu9a1w38n8fcpmd foreign key (CITY_ID) references CITIES;
