alter table CITIES drop foreign key FKic0yipqoyj15kgdfw4yg30agw;
alter table CITIES drop foreign key FKsoag5c17rlm2taywgo5s4j4cj;
alter table ROUTE drop foreign key FKdp4283t8s1pj1sue140wqt5rp;
alter table ROUTE drop foreign key FKrbbfb2cfb4y4pnmny7kxi851;
alter table ROUTE drop foreign key FKhlfn17q71qt21t5r35uavicqu;
alter table ROUTE drop foreign key FK3iybcab2xb7liamrs9a6gr22q;
alter table STATIONS drop foreign key FKrq8w179unt390xxu5480q3o5g;
alter table STATIONS drop foreign key FKdybictqbehfaahxsgpk2g8l7f;
alter table STATIONS drop foreign key FKo539o7bif6yu9a1w38n8fcpmd;
alter table TRIP drop foreign key FKaj2q434sw9yaiimm15mliul6f;
alter table TRIP drop foreign key FKfipav04hhtc2wb9uhoprgfofy;
alter table TRIP drop foreign key FKt2m5dcgww4violuewk41w9961;
alter table USERS drop foreign key FKogvei204bkwyfe2enow9mftjy;
alter table USERS drop foreign key FK3gblpwpmm7u56yo0fff8shblc;
drop table if exists CITIES;
drop table if exists ROUTE;
drop table if exists STATIONS;
drop table if exists TRIP;
drop table if exists USERS;
create table CITIES (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), DISTRICT varchar(32), NAME varchar(32) not null, REGION varchar(32) not null, CREATED_BY integer, MODIFIED_BY integer, primary key (ID)) engine=InnoDB;
create table ROUTE (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), END_TIME time not null, PRICE double precision not null, START_TIME time not null, CREATED_BY integer, MODIFIED_BY integer, DESTINATION_ID integer not null, START_ID integer not null, primary key (ID)) engine=InnoDB;
create table STATIONS (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), APARTMENT varchar(16), HOUSE_NO varchar(16) not null, STREET varchar(32) not null, ZIP_CODE varchar(10) not null, X double precision, Y double precision, PHONE varchar(16), TRANSPORT_TYPE varchar(255) not null, CREATED_BY integer, MODIFIED_BY integer, CITY_ID integer not null, primary key (ID)) engine=InnoDB;
create table TRIP (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), AVAILABLE_SEATS integer not null, END_TIME datetime(6) not null, MAX_SEATS integer not null, PRICE double precision not null, START_TIME datetime(6) not null, CREATED_BY integer, MODIFIED_BY integer, ROUTE_ID integer not null, primary key (ID)) engine=InnoDB;
create table USERS (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), PASSWORD varchar(256) not null, USERNAME varchar(24) not null, CREATED_BY integer, MODIFIED_BY integer, primary key (ID)) engine=InnoDB;
alter table CITIES add constraint cityNameAndRegionUniqueConstraint unique (NAME, REGION);
alter table USERS add constraint UK_h6k33r31i2nvrri9lok4r163j unique (USERNAME);
alter table CITIES add constraint FKic0yipqoyj15kgdfw4yg30agw foreign key (CREATED_BY) references USERS (ID);
alter table CITIES add constraint FKsoag5c17rlm2taywgo5s4j4cj foreign key (MODIFIED_BY) references USERS (ID);
alter table ROUTE add constraint FKdp4283t8s1pj1sue140wqt5rp foreign key (CREATED_BY) references USERS (ID);
alter table ROUTE add constraint FKrbbfb2cfb4y4pnmny7kxi851 foreign key (MODIFIED_BY) references USERS (ID);
alter table ROUTE add constraint FKhlfn17q71qt21t5r35uavicqu foreign key (DESTINATION_ID) references STATIONS (ID);
alter table ROUTE add constraint FK3iybcab2xb7liamrs9a6gr22q foreign key (START_ID) references STATIONS (ID);
alter table STATIONS add constraint FKrq8w179unt390xxu5480q3o5g foreign key (CREATED_BY) references USERS (ID);
alter table STATIONS add constraint FKdybictqbehfaahxsgpk2g8l7f foreign key (MODIFIED_BY) references USERS (ID);
alter table STATIONS add constraint FKo539o7bif6yu9a1w38n8fcpmd foreign key (CITY_ID) references CITIES (ID);
alter table TRIP add constraint FKaj2q434sw9yaiimm15mliul6f foreign key (CREATED_BY) references USERS (ID);
alter table TRIP add constraint FKfipav04hhtc2wb9uhoprgfofy foreign key (MODIFIED_BY) references USERS (ID);
alter table TRIP add constraint FKt2m5dcgww4violuewk41w9961 foreign key (ROUTE_ID) references ROUTE (ID);
alter table USERS add constraint FKogvei204bkwyfe2enow9mftjy foreign key (CREATED_BY) references USERS (ID);
alter table USERS add constraint FK3gblpwpmm7u56yo0fff8shblc foreign key (MODIFIED_BY) references USERS (ID);
