spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3307/germes?useSSL=false
    username: germes
    password: germes
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      base-path: /monitoring
  server:
    port: 9090