germes:
  gateway:
    routes:
      - host: geography
        port: 8080
      - host: ticket
        port: 8080
      - host: trip
        port: 8080
    authentication:
      url: http://user:8080/users
      timeout: 15000