germes:
  gateway:
    routes:
      - host: geography
        port: 8090
      - host: ticket
        port: 8060
      - host: trip
        port: 8050
    authentication:
      url: http://user:8080/users
      timeout: 15000