management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: beans,health,info,mappings
  server:
    port: 9090
germes:
  gateway:
    jwt:
      expiration-in-millis: 1800000
      issuer: Germes
      secret: inFTKqxq8MUK4/aHJ6Uq26PTgucw+9hKlx4q5CE0sr8=