server:
  port: 8040

germes:
  gateway:
    routes:
      - host: localhost
        port: 8090
      - host: localhost
        port: 8060
      - host: localhost
        port: 8050
    authentication:
      url: http://localhost:8070/users
      timeout: 15000